#!/usr/bin/env python
"""
Unified ESP validation comparison for all 4 charge methods:
RESP, AM1-BCC, MPFIT, and MPFIT-GNN (MMomentA)

This script runs in the mmomenta-data environment and handles QM methods.
MPFIT-GNN results are loaded from pre-computed JSON file.
"""

import argparse
import json
import pickle
import sys
from pathlib import Path
import numpy as np
import os

# Import charge fitting methods from openff-PyMPFIT
# Assuming openff-PyMPFIT is in parent directory or PYTHONPATH
try:
    from openff_pymfpit.comparison.compare_charges import (
        RESPFitter, MPFITFitter, AM1BCCAssignFitter
    )
    from openff_pymfpit.comparison.esp_utils import charges_to_esp_openff
except ImportError:
    print("Warning: Could not import from openff-PyMPFIT package")
    print("Trying local import from scripts directory...")
    # Try local import pattern
    sys.path.insert(0, str(Path(__file__).parent.parent / "openff-PyMPFIT" / "examples" / "gdma-charges" / "comparison" / "ZINC_08_03_2025"))
    from compare_charges import RESPFitter, MPFITFitter, AM1BCCAssignFitter
    from esp_utils import charges_to_esp_openff

# Import plotting utilities
sys.path.insert(0, str(Path(__file__).parent.parent / "figures"))
from plot_comparison import create_violin_plots


def run_qm_methods(molecules, output_dir, verbose=False, enable_resp=True,
                   enable_am1bcc=True, enable_mpfit=True):
    """Run QM-based charge methods (RESP, AM1-BCC, MPFIT).

    Parameters
    ----------
    molecules : list
        List of OpenFF molecules
    output_dir : Path
        Directory to save ESP files and results
    verbose : bool
        Print detailed output
    enable_resp : bool
        Enable RESP method
    enable_am1bcc : bool
        Enable AM1-BCC method
    enable_mpfit : bool
        Enable MPFIT method

    Returns
    -------
    dict
        Results for each molecule and method
    """

    # Initialize fitters
    fitters = {}
    if enable_resp:
        fitters["RESP"] = RESPFitter()
    if enable_am1bcc:
        fitters["AM1-BCC"] = AM1BCCAssignFitter()
    if enable_mpfit:
        fitters["MPFIT"] = MPFITFitter()

    results = {
        'mae': {method: [] for method in fitters},
        'rmse': {method: [] for method in fitters},
        'molecules': {}
    }

    for i, molecule in enumerate(molecules):
        mol_name = molecule.name if hasattr(molecule, 'name') else f"mol_{i}"

        if verbose:
            print(f"\n{'='*60}")
            print(f"Molecule {i+1}/{len(molecules)}: {mol_name}")
            print(f"{'='*60}")
            print(f"SMILES: {molecule.to_smiles()}")
            print(f"Formula: {molecule.hill_formula}")

        # Create molecule-specific directory for ESP files
        mol_esp_dir = output_dir / f"mol_{i}"
        mol_esp_dir.mkdir(exist_ok=True)

        mol_results = {}
        esp_reference = None

        # Fit charges with each method
        for method_name, fitter in fitters.items():
            if verbose:
                print(f"  Fitting {method_name}...", end=" ")

            try:
                result = fitter.fit(molecule)
                mol_results[method_name] = result

                # Store ESP reference from first QM method
                if esp_reference is None and hasattr(result, 'esp_record'):
                    esp_reference = result.esp_record

                if verbose:
                    print(f"✓ ({result.time:.2f}s)")
            except Exception as e:
                if verbose:
                    print(f"✗ Failed: {str(e)}")
                else:
                    print(f"⚠ {method_name} failed for {mol_name}: {e}")

        # Save ESP grid files for this molecule (for MPFIT-GNN to use later)
        if esp_reference is not None:
            # Save grid.dat and grid_esp.dat to molecule directory
            # These files should be generated by RESP/MPFIT fitting
            # Copy from current directory to molecule directory if they exist
            if Path("grid.dat").exists() and Path("grid_esp.dat").exists():
                import shutil
                shutil.copy("grid.dat", mol_esp_dir / "grid.dat")
                shutil.copy("grid_esp.dat", mol_esp_dir / "grid_esp.dat")

        # Validate ESP for each method
        if esp_reference is not None:
            for method_name, result in mol_results.items():
                try:
                    esp_metrics = charges_to_esp_openff(
                        molecule,
                        result.charges,
                        esp_reference,
                        verbose=verbose
                    )

                    results['mae'][method_name].append(esp_metrics['mae'])
                    results['rmse'][method_name].append(esp_metrics['rmse'])

                    if not verbose:
                        print(f"✓ {mol_name} {method_name}: MAE={esp_metrics['mae']:.6e}, RMSE={esp_metrics['rmse']:.6e}")

                except Exception as e:
                    print(f"⚠ ESP validation failed for {method_name} on {mol_name}: {e}")

        # Store molecule-level results
        results['molecules'][mol_name] = {
            'smiles': molecule.to_smiles(),
            'methods': {
                method: {
                    'charges': result.charges.tolist(),
                    'time': result.time
                }
                for method, result in mol_results.items()
            }
        }

    return results


def merge_mpfit_gnn_results(qm_results, mpfit_gnn_file):
    """Merge MPFIT-GNN results with QM results.

    Parameters
    ----------
    qm_results : dict
        Results from QM methods
    mpfit_gnn_file : str
        Path to MPFIT-GNN results JSON

    Returns
    -------
    dict
        Merged results
    """

    if not Path(mpfit_gnn_file).exists():
        print(f"⚠ Warning: MPFIT-GNN results file not found: {mpfit_gnn_file}")
        return qm_results

    with open(mpfit_gnn_file, 'r') as f:
        mpfit_gnn_results = json.load(f)

    # Add MPFIT-GNN to results
    qm_results['mae']['MPFIT-GNN'] = mpfit_gnn_results['mae']
    qm_results['rmse']['MPFIT-GNN'] = mpfit_gnn_results['rmse']

    # Merge molecule-level results
    for mol_name, mol_data in mpfit_gnn_results['molecules'].items():
        if mol_name in qm_results['molecules']:
            qm_results['molecules'][mol_name]['methods']['MPFIT-GNN'] = {
                'mae': mol_data['mae'],
                'rmse': mol_data['rmse']
            }

    return qm_results


def main():
    parser = argparse.ArgumentParser(
        description="Compare all 4 charge methods with ESP validation"
    )
    parser.add_argument(
        "--molecules",
        type=str,
        required=True,
        help="Path to pickle file with OpenFF molecules"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="esp_comparison",
        help="Output directory for results and plots"
    )
    parser.add_argument(
        "--mpfit-gnn-results",
        type=str,
        default=None,
        help="Path to pre-computed MPFIT-GNN results JSON (if available)"
    )
    parser.add_argument(
        "--qm-method",
        type=str,
        default="hf",
        help="QM method for ESP calculation (default: hf)"
    )
    parser.add_argument(
        "--qm-basis",
        type=str,
        default="6-31G*",
        help="QM basis set for ESP calculation (default: 6-31G*)"
    )
    parser.add_argument(
        "--no-resp",
        action="store_true",
        help="Disable RESP method"
    )
    parser.add_argument(
        "--no-am1bcc",
        action="store_true",
        help="Disable AM1-BCC method"
    )
    parser.add_argument(
        "--no-mpfit",
        action="store_true",
        help="Disable MPFIT method"
    )
    parser.add_argument(
        "--no-mpfit-gnn",
        action="store_true",
        help="Disable MPFIT-GNN method"
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print detailed results for each molecule"
    )

    args = parser.parse_args()

    # Set QM environment variables
    os.environ['QM_METHOD'] = args.qm_method
    os.environ['QM_BASIS'] = args.qm_basis

    # Create output directory
    output_dir = Path(args.output_dir)
    output_dir.mkdir(exist_ok=True)

    # Load molecules
    print(f"\nLoading molecules from {args.molecules}...")
    with open(args.molecules, 'rb') as f:
        molecules = pickle.load(f)
    print(f"✓ Loaded {len(molecules)} molecules")

    # Run QM methods
    print(f"\n{'='*60}")
    print(f"Running QM-based charge methods...")
    print(f"{'='*60}")

    qm_results = run_qm_methods(
        molecules,
        output_dir,
        verbose=args.verbose,
        enable_resp=not args.no_resp,
        enable_am1bcc=not args.no_am1bcc,
        enable_mpfit=not args.no_mpfit
    )

    # Save QM results
    qm_results_file = output_dir / "qm_methods_results.json"
    with open(qm_results_file, 'w') as f:
        json.dump(qm_results, f, indent=2)
    print(f"\n✓ QM results saved to {qm_results_file}")

    # Merge MPFIT-GNN results if available
    if not args.no_mpfit_gnn and args.mpfit_gnn_results:
        print(f"\nMerging MPFIT-GNN results from {args.mpfit_gnn_results}...")
        qm_results = merge_mpfit_gnn_results(qm_results, args.mpfit_gnn_results)

    # Print summary statistics
    print(f"\n{'='*60}")
    print(f"ESP Validation Summary ({args.qm_method}/{args.qm_basis})")
    print(f"{'='*60}")

    for method in qm_results['mae'].keys():
        if qm_results['mae'][method]:
            mae_values = qm_results['mae'][method]
            rmse_values = qm_results['rmse'][method]
            print(f"\n{method}:")
            print(f"  MAE:  {np.mean(mae_values):.6e} ± {np.std(mae_values):.6e} hartree/e")
            print(f"  RMSE: {np.mean(rmse_values):.6e} ± {np.std(rmse_values):.6e} hartree/e")
            print(f"  N = {len(mae_values)} molecules")

    # Generate publication-quality plots
    print(f"\nGenerating publication-quality plots...")
    plot_file = create_violin_plots(
        qm_results,
        output_dir=str(output_dir),
        qm_method=args.qm_method,
        qm_basis=args.qm_basis
    )

    print(f"\n{'='*60}")
    print(f"Comparison Complete!")
    print(f"{'='*60}")
    print(f"Results saved to: {output_dir}")
    print(f"  - QM methods: {qm_results_file}")
    print(f"  - Violin plots: {plot_file}")


if __name__ == "__main__":
    main()
